# fly.toml app configuration file generated for spotify-payment-bott on 2025-05-01T16:16:05-03:00
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
# --- VERSÃO CORRIGIDA PARA BOT PYTHON (NÃO WEB) ---

app = 'spotify-payment-bott' # Mantenha o nome do seu app
primary_region = 'gru'

# Seção [build] geralmente pode ser mantida ou omitida se o buildpack detectar Python corretamente
[build]
  builder = 'paketobuildpacks/builder:base'

# REMOVIDA a seção [env] que definia PORT=8080 (não precisamos)

# REMOVIDA toda a seção [http_service]

# ADICIONADA/CORRIGIDA a seção [processes] para definir o comando de start
[processes]
  # 'app' é o nome padrão que o Fly costuma procurar para iniciar.
  # Use python3 se 'python' não for o alias correto no ambiente do buildpack.
  # Certifique-se que 'agiota.py' é o nome correto do seu arquivo principal.
  app = "python agiota.py"

# Mantida a configuração da VM
[[vm]]
  size = 'shared-cpu-1x'

# Mantida a configuração do volume persistente
[mounts]
source="bot_data"
destination="/data"