# fly.toml app configuration file generated for spotify-payment-bott on 2025-05-01T16:16:05-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'spotify-payment-bott'
primary_region = 'gru'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[mounts]
source="bot_data"
destination="/data"